# Basic dependabot.yml to update gomod and Github Actions
version: 2
updates:
  # Maintain dependencies for the core library
  - package-ecosystem: "gomod"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    reviewers:
      - "mrz1836"
    assignees:
      - "mrz1836"
    labels:
      - "chore"

  # Maintain dependencies for build tools
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"