# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# GENERAL
# ---------------------------
before:
  hooks:
    - make all
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^test:'

# ---------------------------
# BUILDER
# ---------------------------
build:
  skip: true

# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"

# ---------------------------
# Announce
# ---------------------------
announce:
  slack:
    # Weather its enabled or not.
    # Defaults to false.
    enabled: true

    # Message template to use while publishing.
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .GitURL }}/releases/tag/{{ .Tag }}`
    # message_template: 'Awesome project {{.Tag}} is out!'

    # The name of the channel that the user selected as a destination for webhook messages.
    channel: '#test_slack'

    # Set your Webhook's username.
    # username: ''

    # Emoji to use as the icon for this message. Overrides icon_url.
    # icon_emoji: ''

    # URL to an image to use as the icon for this message.
    # icon_url: ''
