name: run-go-tests

env:
  GO111MODULE: on

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
  #schedule:
  #  - cron: '1 4 * * *'

jobs:
  yamllint:
    name: Run yaml linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-yamllint@v1.4.0
        with:
          fail_on_error: true
          reporter: github-pr-review
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable}}" .'
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Cache code
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run linter and tests
        run: make test-ci
      - name: Write go list
        run: go list -json -m all > go.list
      - name: Ask Nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2
        #continue-on-error: true
      - name: Update code coverage
        run: bash <(curl -s https://codecov.io/bash)
