# ------------------------------------------------------------------------------
#  Update Pre-commit Hooks Workflow
#
#  Purpose: Automatically update pre-commit hooks weekly and open a PR.
#
#  Triggers: Runs every Monday at 08:00 UTC and can be triggered manually.
#
#  Maintainer: @mrz1836
# ------------------------------------------------------------------------------

name: update-pre-commit-hooks

on:
  schedule:
    # ┌─ min ┬─ hour ┬─ dom ┬─ mon ┬─ dow ┐
    - cron: '0 8 * * 1'   # Every Monday at 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "chore: update pre-commit hooks"
          title: "chore: update pre-commit hooks"
          body: "This PR updates all pre-commit hooks to their latest versions."
          branch: "chore/update-pre-commit-hooks"
